site_name: Celeste's Girl
site_url: https://art.tightbytes.com
edit_uri: "http://127.0.0.1:8000/docs/"
use_directory_urls: true
theme:
  name: material
  logo: assets/images/logo.png

  favicon: assets/images/favicon.png

  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: white
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md

  - Charlotte:
      - Charlotte/index.md
      - Structure Tips: Charlotte/Structure.md
      - Emily-Scene01: Charlotte/B2Scene01e.md
      - Robyn-Scene01: Charlotte/B2Scene01r.md
      - Emily-SceneTe: Charlotte/B2Scene00e.md
      - Robyn-SceneTr: Charlotte/B2Scene00r.md
      - Celeste's Girl: Charlotte/CG-Book-One.md

  - Dev:
      - Dev/index.md
      - AI-Illustrious: Dev/ai-Illust.md
      - AI Imaging Models: Dev/aiModels.md
      - Banners and Stuff: Dev/Banners.md
      - Careful Ideas Now: Dev/Careful.md
      - ComfyUI Guidance: Dev/Comfyui.md
      - Domain Transfer: Dev/DomXfer.md
      - General Queries: Dev/General.md
      - Image Prompts: Dev/Prompts.md

  - Blogs:
      - blogs/index.md
      - Blog Sep25: blogs/Blog2509.md
      - Blog Oct25: blogs/Blog2510.md
      - Blog Nov25: blogs/Blog2511.md
      - Blog Dec25: blogs/Blog2512.md
      - Blog Jan26: blogs/Blog2601.md
      - Blog Feb26: blogs/Blog2602.md

  - Visual Art:
      - visual/index.md
      - 2nd Person: visual/Person2.md
      - AI & Emily: visual/Emilyai.md
      - BBoxSEGS: visual/BBoxSEGS.md
      - ComfyUI: visual/Comfyui.md
      - FluxGym: visual/FluxGym.md
      - GIMP Tips: visual/GimpTips.md
      - QwenPrompt: visual/QwenPro.md
      - Videos: visual/Videos.md
      - VScripts: visual/VScripts.md

  - Music:
      - music/index.md

  - Emily:
      - Emily/index.md
      - Emily/Notes26-02-23.md
      - Emily/Notes26-02-27.md

not_in_nav: |
  /Emily/2023/
  /Emily/2024/
  /Emily/2025/
  /Emily/2026/
  /Emily/2602/

plugins:
  - search
  - tags

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
