site_name: Celeste's Girl
site_url: https://art.tightbytes.com
edit_uri: 'http://127.0.0.1:8000/docs/'
use_directory_urls: true
theme:
  name: material
  icon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode
      accent: pink
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - assets/css/customc.css

nav:
  - Home: index.md
  - Celeste's Girl:
    - CelestesGirl/index.md
    - Chapter 1: CelestesGirl/Chap01.md
    - Chapter 2: CelestesGirl/Chap02.md
    - Plot Devt: CelestesGirl/PlotDv.md
  - Dev:
    - Dev/index.md
    - Banners and Stuff: Dev/Banners.md
    - Careful Ideas Now: Dev/Careful.md
    - ComfyUI Guidance: Dev/Comfyui.md
    - Domain Transfer: Dev/DomXfer.md

  - Blogs:
    - blogs/index.md
    - Blog Sep25: blogs/Blog0925.md
    - Blog Oct25: blogs/Blog1025.md
    - Blog Nov25: blogs/Blog1125.md

  - Visual Art:
    - visual/index.md
    - ComfyUI: visual/Comfyui.md
    - AI & Emily: visual/Emilyai.md
    - 2nd Person: visual/Person2.md
    - QwenPrompt: visual/QwenPro.md
    - GIMP Tips: visual/GimpTips.md
    - FluxGym: visual/FluxGym.md
    - Videos: visual/Videos.md
    - VScripts: visual/VScripts.md

plugins:
  - search
  - tags
  
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.tightbytes.com/index.html
    - icon: fontawesome/brands/bluesky
      link: https://bluesky.com/robynsveil
